# One of 'error', 'warn', 'info', 'verbose', debug', 'silly'
loglevel: 'silly'
# Set to true to also parse retain messages at start up
retained: false
# Configuration passed to the node-influx library
influx:
  database: 'mqtt2influx'
  host: '192.168.1.200'
  port: 8086
mqtt:
  # URL to MQTT broker
  url: 'mqtt://192.168.1.200'
  # Configuration passed to the MQTT library
  options:
    username: 'mqtt_username'
    password: 'mqtt_password'
topics:
  - "knx/#"
rewrites:
    - regex: '(knx)\/(status)\/(.*\D.*)\/(.*\D.*)\/(.*\D.*)'
      measurement: '{{T.3}}.{{T.4}}'
      timestamp: '{{M.ts}}'
      tags:
        label: '{{T.5}}'
        dstgad: '{{{M.dstgad}}}'
      fields:
        value: '{{M.val}}'
      continue: true
      repeat: 60
    - regex: 'test\/(.*)'
      measurement: '{{T.1}}'
      tags:
        label: 'label{{T.1}}{{M.label}}'
    - regex: 'knx\/connected'
      measurement: 'knx/connected'
      fields:
        value: '{{M}}'